import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MyNextPwa',
  description: 'Generated by create next app',
  manifest:"/mainfest.json",
  icons:{
    apple:"/icon.png"
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <link rel="manifest" href="/manifest.json" />
      <body className={inter.className+" bg-black h-screen w-full p-4"}>{children}</body>
    </html>
  )
}
